// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLTNut9hOxPhSuw8Oh5VP_ErrQGHIoyV8',
    appId: '1:452269751089:web:b40f75f4218303f0900e10',
    messagingSenderId: '452269751089',
    projectId: 'task-manager-app-934b5',
    authDomain: 'task-manager-app-934b5.firebaseapp.com',
    storageBucket: 'task-manager-app-934b5.firebasestorage.app',
    measurementId: 'G-JF9J07BTXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgyMCYxBpVP62MOC1wiru8FowJ1SvxpWc',
    appId: '1:452269751089:android:e8317bef12e64093900e10',
    messagingSenderId: '452269751089',
    projectId: 'task-manager-app-934b5',
    storageBucket: 'task-manager-app-934b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChBuli46yktUOd6qe1EHuQk54ZebxdblU',
    appId: '1:452269751089:ios:84a7007f7a7df78d900e10',
    messagingSenderId: '452269751089',
    projectId: 'task-manager-app-934b5',
    storageBucket: 'task-manager-app-934b5.firebasestorage.app',
    iosBundleId: 'com.example.taskManagerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChBuli46yktUOd6qe1EHuQk54ZebxdblU',
    appId: '1:452269751089:ios:84a7007f7a7df78d900e10',
    messagingSenderId: '452269751089',
    projectId: 'task-manager-app-934b5',
    storageBucket: 'task-manager-app-934b5.firebasestorage.app',
    iosBundleId: 'com.example.taskManagerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLTNut9hOxPhSuw8Oh5VP_ErrQGHIoyV8',
    appId: '1:452269751089:web:bf74275b303fe6e3900e10',
    messagingSenderId: '452269751089',
    projectId: 'task-manager-app-934b5',
    authDomain: 'task-manager-app-934b5.firebaseapp.com',
    storageBucket: 'task-manager-app-934b5.firebasestorage.app',
    measurementId: 'G-86V90JZ3H1',
  );
}
